version: 0.2

env:
  variables:
    DB_URL: "localhost:5432"
phases:
  pre_build:
    commands:
      - echo pre-build started on `date`
      - pwd
      - ls
      - echo "DB_URL [$DB_URL]"
      - echo "JOB_NAME [$JOB_NAME]"
      - echo "ENV_NAME [$ENV_NAME]"
      - source ./scripts/type1/envs/dev.sh
      - cd ./scripts/type1
      - ./test.sh $ENV_NAME
      - echo "DB_USER [$DB_USER]"
      - echo "DB_PWD [$DB_PWD]"
      - echo "DB_USER2 [$DB_USER2]"
      - echo "DB_PWD2 [$DB_PWD2]"
      - cd ../../
      - source ./scripts/type1/envs/dev.sh
      - echo "DB_USER [$DB_USER] after running source dev.sh from dev-buildspec.yml"
      - echo "DB_PWD [$DB_PWD] after running source dev.sh from dev-buildspec.yml"
  build:
    commands:
      - echo build started on `date`
      - pwd
      - ls
      - echo "DB_URL [$DB_URL]"
      - echo "JOB_NAME [$JOB_NAME]"
      - echo "ENV_NAME [$ENV_NAME]"
      - echo "DB_USER [$DB_USER]"
      - echo "DB_PWD [$DB_PWD]"
      - docker run hello-world

  post_build:
    commands:
      - echo post-build completed on `date`